name: Java Build (sem Maven)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compilar código
      run: |
        mkdir -p out
        javac \
          --module-path "lib" \
          -cp "lib/*" \
          -d out $(find webSocketServer/src -name "*.java")

    - name: Executar programa
      run: |
        java -cp "out:lib/*" Main
